version: '3.8'

frontend:
  build:
    target: development
  volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
  ports:
    - 3000:3000
  user: node
  command: npm start
  stdin_open: true
