name: deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install and Build
        run: npm ci
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy
        run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npm gh-pages -d build -u "TreverHibbs <treverhibbs@gmail.com>"
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
