name: deploy

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

  deploy:
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy-gh-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
